services:
  chatgpt_web:
    image: chenzhaoyu94/chatgpt-web:v2.11.1
    container_name: chatgpt_web
    ports:
      - 3002:3002
    environment:
      - OPENAI_API_KEY=sk-3gPrlTWem5z20sTCjdb6NLQFvjF4DXCz2zNLRHSKqgsvXje0
      - OPENAI_API_BASE_URL=https://api.chatanywhere.com.cn
      - OPENAI_API_MODEL=gpt-3.5-turbo
      - AUTH_SECRET_KEY=lmx050218
      - MAX_REQUEST_PER_HOUR=0
      - TIMEOUT_MS=60000
    restart: unless-stopped
    networks:
      - chatgpt_web

networks:
  chatgpt_web:
    driver: bridge
